"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// Personal Message: Store a person’s name in a variable,...
//and print a message to that person. ...
//Your message should be simple, such as, ....
//“Hello Eric, would you like to learn some Python today?”
let personalMessage = "Ahmed";
console.log(`Assalaam o alikum ${personalMessage},would you like to learn some typescirpt today?`);
